### ISSUE TITLE
multiple to addresses

### ISSUE THREAD

**Issue by acao** [mckeever02/mailtolink#16]
first off, this tool is *fantastic*, thank you!

i noticed when using it, the to: and cc/bcc lines seem to be set up for one email address each on mobile. haven’t looked at the source yet, but it seems this is because `<input type=“email”` is used, which prevents the user from using commas, at least on the ios keyboard for me just now

what do you think is the best option for this?

**Comment by mckeever02** [comment]
Ohh nice find! Yeah it seems you can't enter multiple addresses into email inputs on mobile. Never realised that. Thanks for filing! I've fixed with latest push.
