### ISSUE TITLE
Body?

### ISSUE THREAD

**Issue by mhulse** [mckeever02/mailtolink#4]
Nic simple tool. Cool design.

Have you considered adding the body? (hoping I did not overlook this)

Maybe a check box for "Include body"?

Sometimes I like to have my mailto's [fill the body out with a placeholder](https://stackoverflow.com/a/10356432/922323).

```html
<a href="mailto:someone@example.com?subject=Suggestions&body=name:%0D%0Aemail:">test</a>​
```

Thanks!

**Comment by mckeever02** [comment]
Hey Michael,

There already is a body. See just below the subject where the "A simple markup..." placeholder is. Thats the body. It'll properly encode all spaces and line breaks too. Try it out!

**Comment by mhulse** [comment]
Ahhhh, that's a placeholder!

Lol, as a test, I thought the text you had in there was demo text (not placeholder) and clicked "copy code" and there was no body.

So maybe this is more of a UX feedback ticket then. Perhaps the placeholder could be lighter in color?

Or, have that description above the white box as a heading and leave the body blank?

![screenshot 2019-01-15 10 08 14](https://user-images.githubusercontent.com/218624/51200223-bebd5a00-18ad-11e9-913c-e4bff3994fe5.png)

Anyway, thanks for building this tool! Bookmarked! 👍

**Comment by mhulse** [comment]
Or, maybe like this:

![mailtolink me_](https://user-images.githubusercontent.com/218624/51200555-b285cc80-18ae-11e9-8347-c7fcaa6afad9.png)
