### ISSUE TITLE
Textarea on email body not darkened in dark mode

### ISSUE THREAD

**Issue by harrylewis** [mckeever02/mailtolink#6]
Hey @mckeever02,

This is a really cool project, and I'll be bookmarking it for later use. I like the ability to use this in both a light mode and dark mode. It seems in dark mode, the `textarea` of the body is still white (with white text), so I'm not able to read what I am writing. I think there is an element missing in the CSS declaration in `_scss/_style.scss` on line 373, that would account for this `textarea`.

Keep in mind I am using Chrome v71. I've included a screenshot below.

![screencapture-mailtolink-me-2019-01-16-16_28_30](https://user-images.githubusercontent.com/14965586/51279657-c95e1900-19ab-11e9-823b-d7472605debf.png)

**Comment by mckeever02** [comment]
Whoops. I broke that in my last commit. Should be fixed now (might have to do a couple hard refreshes to clear your cache). 

Thanks for pointing it out.

**Comment by harrylewis** [comment]
Awesome, thanks for making the fix so quickly.
