### ISSUE TITLE
Missing newline in encoded body.

### ISSUE THREAD

**Issue by marsjaninzmarsa** [mckeever02/mailtolink#7]
It should be encoded as `%0D%0A` due to [RFC6068](https://tools.ietf.org/html/rfc6068#section-5).

**Comment by marsjaninzmarsa** [comment]
If correct?

I suppose that `encodeURIComponent()` may not be dedicated for RFC6068, but this service should be...

**Comment by mckeever02** [comment]
You were correct. I did some reading up and `encodeURIComponent()` doesn't properly encode linebreaks as per the RFC6068 spec. I've pushed a fix for this now.
